### ISSUE TITLE
[Data issue] Green Yoshi Amiibo not recognized

### ISSUE THREAD

**Issue by ranma** [metrodroid/metrodroid#718]
## Description of the issue
Amiibo not recognized
Green Yoshi NVL-201 is only recognized as raw data.

## For card-specific issues (delete if not applicable)

- Name of the card type: Amiibo
- Name of the transit agency: Nintendo
- Location: 

Please export a card dump from Metrodroid.

Please do not attach it to this issue -- you may be asked for it later via private email.

## Steps to reproduce

1.
2.
3.

## Expected behaviour
Yoshi recognized as Amiibo

## Actual behaviour
Yoshi recognized as raw data

## Device Logs

Android: Generate a bug report ZIP using the instructions here: https://developer.android.com/studio/debug/bug-report.html

iOS: Generate a sysdiagnose using the instructions here: https://www.jessesquires.com/blog/how-to-sysdiagnose-ios/

Please do not attach it to this issue -- you may be asked for it later via private email.

## Details from About screen:

- Metrodroid version: 3.0.0 (3920)
- Device Model: Pixel 3A (sargo)
- (Android only) Manufacturer: Google
- Android/iOS version: 10 (QQ1A.200105.002)
- (Android only) NFC:
- (Android only) MIFARE Classic:

## Checklist

- [ x] The card appears in the "supported cards" list in Metrodroid on my device.
- [ x] I have copied all the details from the about screen into this bug.
- [x ] For card reading issues, I have exported a card dump from Metrodroid, and can email it privately if needed.
- [x ] I have generated an Android bug report ZIP, and can email it privately if needed.

**Comment by micolous** [comment]
This sounds like a data problem.  Amiibos are kinda strange, but we treat them like transit cards, and this kind of issue is what we'd call "missing data".

NVL-201 appears to be the Yarn series, which we've (supposedly) already got data for: https://github.com/N3evin/AmiiboAPI/blob/b5703ef93413941aa58c46ef42202af6c24c160d/database/amiibo.json#L161-L169

Provided you've not stored any game data with the Amiibo, please use that raw data view to save a copy of the data, and attach it to this bug.

If you have data associated with your Amiibo, or would otherwise keep it private, you can email it to (my github username) at gmail.com.

I'm unable to take further action without a dump of this Amiibo.

**Comment by ranma** [comment]
{
    "tagId": "04138f9a844981",
    "scannedAt": {
        "timeInMillis": 1577641153202,
        "tz": "Europe/Berlin"
    },
    "mifareUltralight": {
        "cardModel": "NTAG215",
        "pages": [
            {
                "data": "04138f10"
            },
            {
                "data": "9a844981"
            },
            {
                "data": "d6480fe0"
            },
            {
                "data": "f110ffee"
            },
            {
                "data": "00000000"
            },
            {
                "data": "6175aba1"
            },
            {
                "data": "6bf590a2"
            },
            {
                "data": "eeb762e9"
            },
            {
                "data": "fe8f6b67"
            },
            {
                "data": "fd890fbf"
            },
            {
                "data": "296cdf77"
            },
            {
                "data": "87348b7e"
            },
            {
                "data": "0f830ebe"
            },
            {
                "data": "54e51589"
            },
            {
                "data": "61c6ff27"
            },
            {
                "data": "3b27b480"
            },
            {
                "data": "a5310dca"
            },
            {
                "data": "b7f67689"
            },
            {
                "data": "f74c72af"
            },
            {
                "data": "f978be7d"
            },
            {
                "data": "727442ba"
            },
            {
                "data": "00030102"
            },
            {
                "data": "00410302"
            },
            {
                "data": "0d12a50f"
            },
            {
                "data": "f85e85bd"
            },
            {
                "data": "f5ef1d90"
            },
            {
                "data": "74c1dcdf"
            },
            {
                "data": "8d5c6a4f"
            },
            {
                "data": "4e508a6f"
            },
            {
                "data": "a806cb73"
            },
            {
                "data": "a3dbcba2"
            },
            {
                "data": "a12b8d73"
            },
            {
                "data": "d2887050"
            },
            {
                "data": "d6f9c8e9"
            },
            {
                "data": "0b305bf4"
            },
            {
                "data": "10fa1cc6"
            },
            {
                "data": "ed3ca211"
            },
            {
                "data": "f9552d82"
            },
            {
                "data": "eac0ad99"
            },
            {
                "data": "ac78319a"
            },
            {
                "data": "26f18355"
            },
            {
                "data": "886b2972"
            },
            {
                "data": "ff7009b0"
            },
            {
                "data": "ec9fe578"
            },
            {
                "data": "d40d0288"
            },
            {
                "data": "8f0e5a1d"
            },
            {
                "data": "0cfc63c5"
            },
            {
                "data": "23c3bea6"
            },
            {
                "data": "1de98fe4"
            },
            {
                "data": "712120cb"
            },
            {
                "data": "3632eb92"
            },
            {
                "data": "eb95184c"
            },
            {
                "data": "be86d764"
            },
            {
                "data": "120a2aef"
            },
            {
                "data": "05c8675f"
            },
            {
                "data": "9919ddc3"
            },
            {
                "data": "40ae8bf9"
            },
            {
                "data": "329ea54b"
            },
            {
                "data": "4d5defa7"
            },
            {
                "data": "d3a3af06"
            },
            {
                "data": "bc2a5dde"
            },
            {
                "data": "cab8f7f5"
            },
            {
                "data": "d9ddbc33"
            },
            {
                "data": "91037c89"
            },
            {
                "data": "28cc086c"
            },
            {
                "data": "15109d35"
            },
            {
                "data": "bde90dd4"
            },
            {
                "data": "57723ce6"
            },
            {
                "data": "80777d0f"
            },
            {
                "data": "b315d970"
            },
            {
                "data": "e757ba80"
            },
            {
                "data": "e44d0dd2"
            },
            {
                "data": "17923ca9"
            },
            {
                "data": "230df832"
            },
            {
                "data": "19738ef6"
            },
            {
                "data": "cc351f24"
            },
            {
                "data": "60013aa2"
            },
            {
                "data": "75d44d97"
            },
            {
                "data": "084cadc0"
            },
            {
                "data": "5194ff45"
            },
            {
                "data": "00d6f8d4"
            },
            {
                "data": "7deafa20"
            },
            {
                "data": "5144af55"
            },
            {
                "data": "3fd9e7b7"
            },
            {
                "data": "2893c565"
            },
            {
                "data": "4c44130b"
            },
            {
                "data": "c626bab7"
            },
            {
                "data": "e606e522"
            },
            {
                "data": "60402460"
            },
            {
                "data": "dd96bc75"
            },
            {
                "data": "6fa3bea3"
            },
            {
                "data": "e79b5d59"
            },
            {
                "data": "c5605f03"
            },
            {
                "data": "d72e4eaa"
            },
            {
                "data": "e145aec1"
            },
            {
                "data": "5c9d0eb8"
            },
            {
                "data": "6e560c88"
            },
            {
                "data": "44363176"
            },
            {
                "data": "481951bd"
            },
            {
                "data": "f7be033e"
            },
            {
                "data": "951c1bb2"
            },
            {
                "data": "6a5306e6"
            },
            {
                "data": "fd4a4d9d"
            },
            {
                "data": "d84282a9"
            },
            {
                "data": "c0b31240"
            },
            {
                "data": "b604511b"
            },
            {
                "data": "0f26565f"
            },
            {
                "data": "eb571e49"
            },
            {
                "data": "f7ff9e2c"
            },
            {
                "data": "7ea2463a"
            },
            {
                "data": "cb453dd4"
            },
            {
                "data": "b1b2f6cb"
            },
            {
                "data": "9058b483"
            },
            {
                "data": "c7c73860"
            },
            {
                "data": "4031d937"
            },
            {
                "data": "e5a04d4c"
            },
            {
                "data": "5b25c387"
            },
            {
                "data": "ead92144"
            },
            {
                "data": "0530499c"
            },
            {
                "data": "d1fd336b"
            },
            {
                "data": "4a1dc16c"
            },
            {
                "data": "6286e2cc"
            },
            {
                "data": "e779c478"
            },
            {
                "data": "dbb0c801"
            },
            {
                "data": "76c920a6"
            },
            {
                "data": "47781e80"
            },
            {
                "data": "032d205d"
            },
            {
                "data": "a5e83925"
            },
            {
                "data": "d8b1055b"
            },
            {
                "data": "4e203995"
            },
            {
                "data": "01000fbd"
            },
            {
                "data": "00000004"
            },
            {
                "data": "5f000000"
            },
            {
                "data": "00000000"
            },
            {
                "data": "00000000"
            }
        ]
    }
}

**Comment by ranma** [comment]
Notably it looks like the 0x0003010200410302 sequence does appear inside the raw data.

**Comment by micolous** [comment]
Page 4 looks different to what Metrodroid expects: it [should](https://www.3dbrew.org/wiki/Amiibo#Page_layout) start with `a5`, your Yoshi has `00000000`.  As a result, Metrodroid doesn't think that this is an Amiibo.

After applying the change in #733, this is recognised as an Amiibo:

```
% ./metrodroid-cli parse ~/dev/cards/amiibo/green-yoshi-nvl-201.json
card UID = <04138f9a844981>
   name = Amiibo
   serial = null
   info
      Type: Yarn
      Character: Yoshi [0x3]
      Character variant: 1
      Model number: 65
      Series: Yoshi's Woolly World
```

I think this is because this Amiibo has never been written to by Nintendo hardware / software, is that correct?

**Comment by ranma** [comment]
Could be, but I'm not fully sure. Thanks for the investigation!
