### ISSUE TITLE
[BUG] Controls overlap when font and display size set to largest

### ISSUE THREAD

**Issue by franklinbill** [metrodroid/metrodroid#744]
## Description of the issue
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 2.9.37, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
<img width="476" alt="bug-farebot" src="https://user-images.githubusercontent.com/18572115/103218339-ae490180-4955-11eb-8eae-d8d316b0b1e5.png">

## For card-specific issues (delete if not applicable)

- Name of the card type:
- Name of the transit agency:
- Location:

Please export a card dump from Metrodroid.

Please do not attach it to this issue -- you may be asked for it later via private email.

## Steps to reproduce

1.use the largest font and display
2.see the issue

## Expected behaviour
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.

## Actual behaviour
As shown in the figure, in the first page, the text overlap each other. 

## Device Logs

Android: Generate a bug report ZIP using the instructions here: https://developer.android.com/studio/debug/bug-report.html

iOS: Generate a sysdiagnose using the instructions here: https://www.jessesquires.com/blog/how-to-sysdiagnose-ios/

Please do not attach it to this issue -- you may be asked for it later via private email.

## Details from About screen:

- Metrodroid version: 2.9.37
- Device Model:  Google nexus 6
- (Android only) Manufacturer:
- Android/iOS version: 8.0
- (Android only) NFC:
- (Android only) MIFARE Classic:

## Checklist

- [√] The card appears in the "supported cards" list in Metrodroid on my device.
- [√] I have copied all the details from the about screen into this bug.
- [√] For card reading issues, I have exported a card dump from Metrodroid, and can email it privately if needed.
- [√] I have generated an Android bug report ZIP, and can email it privately if needed.

**Comment by micolous** [comment]
Oops, that's definitely not intended.  There's no scrolling on that view at all, so it can't handle having the font size "too large".

Are there any views other than the About screen which you see this problem on?

**Comment by micolous** [comment]
I ran the current development version of Metrodroid in an emulator (emulating Pixel 3), with font and display size set to largest, and had a look:

## Views that look OK:

* Main screen
* Supported cards
* History
* Card view:
   * Ticket with name, balance and expiry
   * Pass with passenger count, status, and expiry
   * Trip history entries with agency, start and end stops, start and end times, and price
   * Info
* Advanced card info raw/manufacturing info views
   * MFC
   * MFD
   * FeliCa
   * Unsupported card banner

## Views that have problems:

* About screen (overlapping elements, as above)

* Trip map (map labels do not appear to be scaled – but unsure what we can do about this)

   ![Screenshot_1609374484](https://user-images.githubusercontent.com/246847/103388079-47953500-4b5b-11eb-9181-2cfd3e364094.png)

* Advanced card info: title and subtitle can get cut off; but unsure how fixable that is. 

   ![Screenshot_1609374826](https://user-images.githubusercontent.com/246847/103388268-38fb4d80-4b5c-11eb-9a04-d1d665a782b8.png)

* Preferences: some of the option names in Developer Options and for Map settings are cut off; but these are also explained in the description below it.

   ![Screenshot_1609375030](https://user-images.githubusercontent.com/246847/103388378-c50d7500-4b5c-11eb-99bc-ab7251fce5d7.png)

   It looks like the Settings app has properly word wrapped preferences entries, so it should be possible to fix this one with some tweaks.

**Comment by franklinbill** [comment]
Thanks*100000 for your reply! It's not bad on other pages. I agree with your analysis of the problem. Looking forward to your new version.

**Comment by micolous** [comment]
Progress so far on staged changes (not pushed live):

## Use multi-line preference titles everywhere:

Screenshot at largest size; now long settings titles aren't cut off anymore.

![Screenshot_1609383408](https://user-images.githubusercontent.com/246847/103392049-1a9f4d00-4b70-11eb-9ec5-4565d5c08e09.png)

This was also a problem when running Metrodroid in German at default size, which also gets fixed up by this change:

 ![Screenshot_1609383572](https://user-images.githubusercontent.com/246847/103392129-85508880-4b70-11eb-87ff-5046a768b14b.png)

## About screen fixes

At largest size, the view scrolls (scroll bar shows up when you touch to scroll):

![Screenshot_1609383215](https://user-images.githubusercontent.com/246847/103392157-a1542a00-4b70-11eb-928e-ca2b290a6a9c.png)

At default size, elements are still spaced out as they were before:

![Screenshot_1609383231](https://user-images.githubusercontent.com/246847/103392198-c0eb5280-4b70-11eb-9060-953d804c121a.png)

**Comment by micolous** [comment]
Unfortunately, it's very difficult to fix the app title bars used on the `Map` and `Advanced Card Info` views, because they're part of `ActionBar` (in the Android platform and AppCompat Support Library), which forces all titles and subtitles to be ellipsized, with no way to change it.

The only way around this would be to use custom display logic, which is extremely tedious to work with, and risks introducing other problems.  It'd be nice if the AppCompat library would handle this for us.

In the `Advanced Card Info` screen, the scan time is available from the card history list, which works properly when set to large size.  The card's raw UID is only shown in the history screen if the card is unknown – but there is limited utility showing this for _known_ cards.

If you're looking at writing transit data parsers and _really want it_, the JSON/XML exports have this as an attribute, and chances are you'll want to work with those files anyway (eg: loading binary data into a hex editor so that you get a nice display of all the binary data structures)... so I'm not concerned about this being unavailable.

In the `Map` screen, the start and end stations are also available in the trip history.  It's easy for these to be cut off anyway even at default font sizes with long station names (eg: Queensland bus stop names).
